### ISSUE TITLE
Doesn't build with dbus 1.0.1

### ISSUE THREAD

**Issue by felixonmars** [jaor/xmobar#346]
```
[ 9 of 57] Compiling IPC.DBus         ( src/IPC/DBus.hs, dist/build/xmobar/xmobar-tmp/IPC/DBus.dyn_o )

src/IPC/DBus.hs:46:32: error:
    Ambiguous occurrence ‘interfaceName’
    It could refer to either ‘DBus.Client.interfaceName’,
                             imported from ‘DBus.Client’ at src/IPC/DBus.hs:18:1-18
                          or ‘IPC.DBus.interfaceName’, defined at src/IPC/DBus.hs:33:1
   |
46 | sendSignalMethod mvst = method interfaceName sendSignalName
   |                                ^^^^^^^^^^^^^
```

Hiding the name brings more errors:

```
[ 9 of 57] Compiling IPC.DBus         ( src/IPC/DBus.hs, dist/build/xmobar/xmobar-tmp/IPC/DBus.dyn_o )

src/IPC/DBus.hs:43:34: error:
    • Couldn't match expected type ‘Interface’
                  with actual type ‘[Method]’
    • In the third argument of ‘export’, namely
        ‘[sendSignalMethod mvst]’
      In a stmt of a 'do' block:
        export client objectPath [sendSignalMethod mvst]
      In the expression:
        do client <- connectSession
           requestName client busName [nameDoNotQueue]
           export client objectPath [sendSignalMethod mvst]
   |
43 |         export client objectPath [ sendSignalMethod mvst ]
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^

src/IPC/DBus.hs:46:25: error:
    • Variable not in scope:
        method
          :: InterfaceName
             -> MemberName
             -> Signature
             -> Signature
             -> (MethodCall -> IO Reply)
             -> Method
    • Perhaps you meant data constructor ‘Method’ (imported from DBus.Client)
   |
46 | sendSignalMethod mvst = method interfaceName sendSignalName
   |                         ^^^^^^

src/IPC/DBus.hs:58:18: error:
    • Variable not in scope: replyReturn :: [a0] -> Reply
    • Perhaps you meant data constructor ‘ReplyReturn’ (imported from DBus.Client)
   |
58 |         return ( replyReturn [] )
   |                  ^^^^^^^^^^^
```

**Comment by jaor** [comment]
what version of xmobar are you trying? in the current xmobar.cabal we
explicitly set dbus < 1.0 because of that, so this error shouldn't pop
up...

**Comment by felixonmars** [comment]
I am using xmobar 0.25. Looks like the version limit is not present on the hackage tarball.

Will xmobar support the new dbus soon?

**Comment by jaor** [comment]
i don't know yet when we will support the new dbus version (dbus support
was a contribution and i don't know that code well).  in the meantime,
i've pushed to hackage version 0.26, with version limits.

**Comment by anthraxx** [comment]
maybe @jotrk has interest to jump in again and port it to the new API? :cat:

**Comment by jotrk** [comment]
Sorry to disappoint you, but I rarely write code these days. And I didn't touch Haskell for more than two years now.

**Comment by jaor** [comment]
The fix for dbus 1.x is now in. Closing!
